name: rsocket
version: 0.1.2
description: RSocket for Dart
homepage: https://github.com/rsocket/rsocket-dart
repository: https://github.com/rsocket/rsocket-dart.git
issue_tracker: https://github.com/rsocket/rsocket-dart/issues
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  rxdart: ^0.27.1
dev_dependencies:
  test: ^1.6.0
