name: rsocket
version: 1.0.0
description: RSocket for Dart
homepage: https://github.com/rsocket/rsocket-dart
repository: https://github.com/rsocket/rsocket-dart.git
issue_tracker: https://github.com/rsocket/rsocket-dart/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  web_socket_channel:
  universal_io:
dev_dependencies:
  test: ^1.19.2
